In [1]:
import pandas as pd

In [7]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Saskia'],
    'Math Score': [85, 78, 92, 88, 90],
    'English Score': [95, 85, 89, 76, 88],
    'Science Score': [78, 83, 85, 90, 92]
}

df = pd.DataFrame(data)
df.head()

      Name  Math Score  English Score  Science Score
0    Alice          85             95             78
1      Bob          78             85             83
2  Charlie          92             89             85
3    David          88             76             90
4   Saskia          90             88             92

In [8]:
df['Average Score'] = df[['Math Score', 'English Score', 'Science Score']].mean(axis=1)
print(df)

      Name  Math Score  English Score  Science Score  Average Score
0    Alice          85             95             78      86.000000
1      Bob          78             85             83      82.000000
2  Charlie          92             89             85      88.666667
3    David          88             76             90      84.666667
4   Saskia          90             88             92      90.000000

In [9]:
high_math_scorers = df[df['Math Score'] > 85]
print(high_math_scorers)

      Name  Math Score  English Score  Science Score  Average Score
2  Charlie          92             89             85      88.666667
3    David          88             76             90      84.666667
4   Saskia          90             88             92      90.000000

In [10]:
sorted_df = df.sort_values(by='Average Score', ascending=False)
print(sorted_df)

      Name  Math Score  English Score  Science Score  Average Score
4   Saskia          90             88             92      90.000000
2  Charlie          92             89             85      88.666667
0    Alice          85             95             78      86.000000
3    David          88             76             90      84.666667
1      Bob          78             85             83      82.000000

In [11]:
grouped_df = df.groupby('English Score')['Math Score'].mean()
grouped_df.head()

English Score
76    88.0
85    78.0
88    90.0
89    92.0
95    85.0
Name: Math Score, dtype: float64