In [10]:
import re

words = 'MySkill: portal for any learning path'

match = re.search(r'portal', words)

print('Start Index:', match.start())
print('End Index:', match.end())

Start Index: 9
End Index: 15

In [11]:
find_dot = "This is a dot ...."

match1 = re.search(r'.', find_dot)

match2 = re.search(r'\.', find_dot)

print(match1)
print(match2)

<re.Match object; span=(0, 1), match='T'>
<re.Match object; span=(14, 15), match='.'>

In [13]:
story = "On 4th November I will go to ancol, the ticker price only 25000 Rupiah. It's a discount price. Last time I went to Ancol was in 2 January 2022 and the ticket price was 30000 Rupiah"

number1 = re.compile('\d')
number2 = re.compile('\d+')

print(re.findall(number1, story))

print(re.findall(number2, story))

['4', '2', '5', '0', '0', '0', '2', '2', '0', '2', '2', '3', '0', '0', '0', '0']
['4', '25000', '2', '2022', '30000']

In [24]:
from re import split

data = 'My name is Bayu Sedana, I was born in Majene 26th November 1996 at 02:00 PM'

print(split('\W+', data))

['My', 'name', 'is', 'Bayu', 'Sedana', 'I', 'was', 'born', 'in', 'Majene', '26th', 'November', '1996', 'at', '02', '00', 'PM']